services:
  - type: web
    name: reporte-averias
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.12.3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
